import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
config.autoAddCss = false

import { faInstagram, faFacebook, faLinkedin, faYoutube } from '@fortawesome/free-brands-svg-icons'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Veca Vision Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head><meta name="viewport" content="width=device-width, initial-scale=1.0"></meta></head>

      <body className={inter.className}>
        
        <div className="flex flex-col h-screen justify-between">
          <header>
            <div className="hidden md:flex z-10 sticky top-0 bg-[#000] border-b border-white justify-between items-center md:pl-10 md:pr-48 xl:pl-96 xl:pr-96">
              <Link href="/" className="flex items-center grayscale hover:grayscale-0 hover:text-vvm-lightblue ease-in-out duration-300">
                <Image src="/VVM-images/Veca-Vision2.png" alt="/" width={75} height={75} className="m-0 p-0" />
                Veca Vision Media
              </Link>
              <div className="flex justify-between w-1/4 space-x-6">
              <Link href="/services" className="hover:text-vvm-teal relative w-fit block after:block after:content-[''] after:absolute after:h-[2px] after:bg-vvm-teal after:w-full after:scale-x-0 after:hover:scale-x-100 after:transition after:duration-300 after:origin-left">Services</Link>
              <Link href="/portfolio" className="hover:text-vvm-lightblue relative w-fit block after:block after:content-[''] after:absolute after:h-[2px] after:bg-vvm-lightblue after:w-full after:scale-x-0 after:hover:scale-x-100 after:transition after:duration-300 after:origin-left">Portfolio</Link>
              <Link href="/about" className="hover:text-vvm-blue relative w-fit block after:block after:content-[''] after:absolute after:h-[2px] after:bg-vvm-blue after:w-full after:scale-x-0 after:hover:scale-x-100 after:transition after:duration-300 after:origin-left">About</Link>
              <Link href="/contact" className="hover:text-vvm-pink relative w-fit block after:block after:content-[''] after:absolute after:h-[2px] after:bg-vvm-pink after:w-full after:scale-x-0 after:hover:scale-x-100 after:transition after:duration-300 after:origin-left">Contact</Link>
              </div>
            </div>

            <div className="flex md:hidden z-10 sticky top-0 bg-[#000] border-b border-white pl-6 pr-6 justify-between">
              <Link href="/" className="flex items-center ease-in-out duration-300">
                <Image src="/VVM-images/Veca-Vision2.png" alt="/" width={75} height={75} className="m-0 p-0" />
              </Link>
              <div className="space-y-2 content-center">
                <span className="block w-6 border-b" />
                <span className="block w-6 border-b" />
              </div>
            </div>

          </header>
          
          <div className="mb-auto">
            {children}
          </div>
          
          
          <footer className="border-t border-white pt-3 pb-2">

            <div className="flex justify-evenly">
              <div>
                Follow Us
                <div className="space-x-4">
                  <a href='https://www.facebook.com/VecaMedia' target='_blank' rel='noopener noreferrer' ><FontAwesomeIcon icon={faFacebook} className="hover:text-vvm-teal hover:cursor-pointer" /></a>
                  <a href='https://www.instagram.com/vecavisionmedia/' target='_blank' rel='noopener noreferrer' ><FontAwesomeIcon icon={faInstagram} className="hover:text-vvm-lightblue hover:cursor-pointer" /></a>
                  <a href='https://www.linkedin.com/in/jaiden-veca-0a71b6292/' target='_blank' rel='noopener noreferrer' ><FontAwesomeIcon icon={faLinkedin} className="hover:text-vvm-blue hover:cursor-pointer" /></a>
                  <a href='https://www.youtube.com/channel/UC59xCCLBkobyj5wyEphwQmg' target='_blank' rel='noopener noreferrer' ><FontAwesomeIcon icon={faYoutube} className="hover:text-vvm-pink hover:cursor-pointer" /></a>
                </div>
              </div>
              <div>
                Subscribe
              </div>
              <div>
                Contact US
                <div className="font-thin">(406)595-6899</div>
                <div className="font-thin">veca.vision@gmail.com</div>
              </div>
            </div>
            <div className="mt-3 font-thin text-xs flex justify-evenly">Copyright &copy; 2024 Veca Vision Media - All Rights Reserved.</div>


          </footer>


        </div>
      </body>
    </html>
  );
}
